Create a Pipelline job
e.g.
  steps {           
            sh 'pwd'
            sh 'cp -R helm/* .'
	    sh 'ls -ltr'
            sh 'pwd'
            sh '/usr/local/bin/helm upgrade --install petclinic-app petclinic  --set image.repository=registry.hub.docker.com/omeshwar/petclinic --set image.tag=13'              			
        }          

"pwd": /var/lib/jenkins/workspace/<CD Job Name> e.g. DeployImage

"cp -R helm/* .": Copy the helm chart insdide the dir helm to the pwd 
e.g. we have helm chart "petclicin" in this example so the command is executing as "cp -R helm/petclinic /var/lib/jenkins/workspace/DeployImage"
This will help in executing in the various yaml files like deployment, service, vars etc. inside the helm chart.

"/usr/local/bin/helm upgrade --install petclinic-app petclinic  --set image.repository=registry.hub.docker.com/omeshwar/petclinic --set image.tag=13"
/usr/local/bin/helm: This is the location of executable file "helm" in the jenkins server
upgrade --install: The command --install helps in the first time installation of the app e.g. petclinic-app ,however, re-run of the app will need upgrade as install will error.
petclinic-app: The app name is what we have provided in the deployment.yaml
template:
    metadata:
      labels:
        app: petclinic-app    
petclinic: Name of the repository in the git-hub (SCM) 
--set image.repository=registry.hub.docker.com/omeshwar/petclinic --set image.tag=13: This is run time command that helps in over wrting the image name provided in the 
valkue.yml file.
image:
  repository: omeshwar/petclinicimage  (<Repository-name:Image-name>)
  tag: latest
  pullPolicy: IfNotPresent
e.g. our values.yaml image name and tag matches with the image name in the docker-hub repo then the command "/usr/local/bin/helm upgrade --install petclinic-app petclinic"
is good to deploy the imgae to the cluster, however, since actualimage name "petclinic, tag:13" are different so we are we are passing the additonal run command.
Tried with "--set image.repository=registry.hub.docker.com/omeshwar/petclinic --set image.tag=1" and image get created but POD crahsdroff with error could not pull the image 
from the docker-hub registry.
	

	
